---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  issuerRef:
    name: linkerd-webhook-trust-anchor
    kind: ClusterIssuer
  secretName: linkerd-sp-validator-k8s-tls
  duration: 2160h
  renewBefore: 168h
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
    - linkerd-sp-validator.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  issuerRef:
    name: linkerd-webhook-trust-anchor
    kind: ClusterIssuer
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 2160h
  renewBefore: 168h
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
    - linkerd-proxy-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  issuerRef:
    name: linkerd-webhook-trust-anchor
    kind: ClusterIssuer
  secretName: linkerd-policy-validator-k8s-tls
  duration: 2160h
  renewBefore: 168h
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
    - linkerd-policy-validator.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
  usages:
    - server auth
