---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-webhook-trust-anchor
  namespace: cert-manager # Cert Manager expects the certificates used to sign cluster issuers to be in its own namespace
spec:
  issuerRef:
    name: linkerd-selfsigned
    kind: ClusterIssuer
  secretName: linkerd-webhook-trust-anchor
  duration: 4320h
  renewBefore: 336h
  commonName: webhook.linkerd.cluster.local
  dnsNames:
    - webhook.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-webhook-trust-anchor
spec:
  ca:
    secretName: linkerd-webhook-trust-anchor
