---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  issuerRef:
    name: linkerd-selfsigned
    kind: ClusterIssuer
  secretName: linkerd-trust-anchor
  duration: 87600h
  renewBefore: 2160h
  commonName: root.linkerd.cluster.local
  dnsNames:
    - root.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
