apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 60m
  chart:
    spec:
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: identityTrustAnchorsPEM
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    proxyInjector:
      externalSecret: true
      injectCaFrom: linkerd/linkerd-proxy-injector
    profileValidator:
      externalSecret: true
      injectCaFrom: linkerd/linkerd-sp-validator
    policyValidator:
      externalSecret: true
      injectCaFrom: linkerd/linkerd-policy-validator
  dependsOn:
    - name: linkerd-crds
      namespace: linkerd

# For more information on using cert-manager to automatically rotate tls credentials,
# See the following links:
# https://linkerd.io/2.14/tasks/automatically-rotating-control-plane-tls-credentials/
# https://cert-manager.io/docs/concepts/ca-injector/#injecting-ca-data-from-a-certificate-resource
# https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/values.yaml
# https://github.com/BuoyantIO/gitops-linkerd/blob/main/infrastructure/linkerd/linkerd-control-plane.yaml
