variable "commit_flux_manifests" {
  description = "Set to `false` to disable committing manifests generated by initial Flux setup."
  type        = bool
  default     = true
}

variable "create_github_branch" {
  description = "Set to `true` to allow Terraform to manage the lifecycle of the Github branch."
  type        = bool
  default     = false
}

variable "github_owner" {
  description = "Owner of Github repository containing Flux configuration."
  type        = string
}

variable "github_repository" {
  description = "Name of repository containing Flux configuration."
  type        = string
}

variable "github_branch" {
  description = "Branch of Github repo to sync with Flux."
  type        = string
  default     = "main"
}

variable "github_path" {
  description = "Path in Github repo that Flux will sync with."
  type        = string
}

variable "github_path_prefix" {
  description = "Path prefix for `var.github_path`."
  type        = string
  default     = "clusters"
}

variable "namespace" {
  description = "Namespace to install Flux in."
  type        = string
  default     = "flux-system"
}

