---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/controllers/overlays/istio-dev/istio
  prune: true
  wait: true
