version: ">= 0.13.0, < 1.0.0"

formatter: markdown

header-from: versions.tf
footer-from: ""

sections:
  hide: []
  show: []

content: ""

output:
  file: "README.md"
  mode: replace
  template: |-
    # Use Terraform and Flux to manage a K8s Cluster

    This will setup a k8s kubernetes cluster on your local machine and setup the following things.
    * [Traefik](https://doc.traefik.io/traefik/) for ingress on [traefik.localhost](http://traefik.localhost)
    * [Flux](https://fluxcd.io/) for gitops
    * [Weave Gitops](https://docs.gitops.weave.works/docs/intro-weave-gitops/) to visualize flux on [flux.localhost](http://flux.localhost)
    * [Linkerd](https://linkerd.io/) for a service mesh
    * [Cert Manager](https://cert-manager.io/docs/) for good old SSL and mTLS
    * [Podinfo](https://github.com/stefanprodan/podinfo) to test that everything is working on [podinfo.localhost](http://podinfo.localhost)

    ## Prerequisites
    * Docker (Just be sure it works with Kind)
        * [Docker Desktop](https://www.docker.com/products/docker-desktop/)
        * [Podman](https://podman.io/docs/installation)
        * [Colima](https://github.com/abiosoft/colima)
    * [Kind](https://kind.sigs.k8s.io/)
    * [Terraform](https://www.terraform.io/docs/index.html)
    * (optional) [Taskfile](https://taskfile.dev/installation/)

    This Terraform project uses the Github provider. In order to authenticate to Github, you will need to do 1 of the following:
    * Install the [Github CLI](https://cli.github.com/) and authenticate through that
    * Create a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) with the `repo` scope, and set the `GITHUB_TOKEN` env var to your PAT.

    ## Usage
    ### Setup
    This configuration will create a cluster named after the selected Terraform workspace.</br>
    It will also create a branch in your github repository named `flux-${terraform.workspace}`,</br>
    and configure this branch as the source of truth for the Flux instance in the cluster.</br>

    If a directory `flux/clusters/${terraform.workspace} doesn't exist, an empty Flux configuration will be created.</br>

    ```
    task ws -- select -or-create linkerd
    task apply
    ```

    ### Cleanup
    ```
    task destroy
    ```

    See the [Flux README](flux/README.md) for more information on how flux works, and how the directory structure is set up.

    {{ .Content }}

    This README was generated by [terraform-docs](https://terraform-docs.io).

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true