version: ">= 0.13.0, < 1.0.0"

formatter: markdown

header-from: versions.tf
footer-from: ""

sections:
  hide: []
  show: []

content: ""

output:
  file: "README.md"
  mode: replace
  template: |-
    # Use Terraform and K3d to manage a K3s Cluster

    This will setup a k3d kubernetes cluster on your local machine and setup the following things.
    * [Traefik](https://doc.traefik.io/traefik/) for ingress on traefik.lvh.me:8080
    * [Flux](https://fluxcd.io/) for gitops
    * [Weave Gitops](https://docs.gitops.weave.works/docs/intro-weave-gitops/) to visualize flux on flux.lvh.me:8080
    * [Linkerd](https://linkerd.io/) for a service mesh
    * [Cert Manager](https://cert-manager.io/docs/) for good old SSL and mTLS

    ## Prerequisites
    * [K3d](https://k3d.io)
    * [Terraform](https://www.terraform.io/docs/index.html)

    ## Usage
    Setup
    ```
    terraform apply
    ```

    Cleanup
    ```
    terraform destroy
    ```

    See the [Flux README](flux/README.md) for more information on how flux works, and how the directory structure is set up.

    {{ .Content }}

    This README was generated by [terraform-docs](https://terraform-docs.io).

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true