---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    toolkit.fluxcd.io/tenant: app-team
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage
  namespace: backstage
spec:
  enableSuperuserAccess: true
  instances: 3
  storage:
    size: 1Gi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 24h
  url: https://backstage.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 60m
  chart:
    spec:
      chart: backstage
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: backstage
      interval: 48h
  valuesFrom:
    - kind: Secret
      name: backstage-superuser
      valuesKey: host
      targetPath: backstage.appConfig.backend.database.connection.host
    - kind: Secret
      name: backstage-superuser
      valuesKey: port
      targetPath: backstage.appConfig.backend.database.connection.port
    - kind: Secret
      name: backstage-superuser
      valuesKey: user
      targetPath: backstage.appConfig.backend.database.connection.user
    - kind: Secret
      name: backstage-superuser
      valuesKey: password
      targetPath: backstage.appConfig.backend.database.connection.password
  values:
    backstage:
      appConfig:
        backend:
          database:
            client: pg
  install:
    remediation:
      retries: 3
  # Default values: https://github.com/backstage/charts/blob/main/charts/backstage/values.yaml
