---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/linkerd
  - ./linkerd-viz.ingress.yaml
patches:
  - path: linkerd-viz.values.yaml
    target:
      kind: HelmRelease
      name: linkerd-viz
      namespace: linkerd-viz
