---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 60m
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: istio-system
      interval: 48h
  dependsOn:
    - name: istio-ingress
      namespace: istio-system
