---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    istio-injection: enabled
