---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/controllers/overlays/linkerd-dev/cert-manager
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/controllers/overlays/linkerd-dev/linkerd
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  dependsOn:
    - name: linkerd
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/controllers/overlays/linkerd-dev/traefik
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  dependsOn:
    - name: linkerd
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/controllers/overlays/linkerd-dev/weave-gitops
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  # dependsOn:
  #   - name: linkerd
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/controllers/overlays/linkerd-dev/cloudnative-pg
  prune: true
