---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  toolkit.fluxcd.io/tenant: sre-team
resources:
  - ../../base/weave-gitops
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
