---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    additionalArguments:
      - "--api.insecure=true"
    gateway:
      listeners:
        web:
          namespacePolicy: All
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: "Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
        entryPoints: ["traefik", "web"]
    service:
      type: NodePort
    ports:
      web:
        nodePort: 32080
      websecure:
        nodePort: 32443
    nodeSelector:
      ingress-controller: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
