---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    additionalArguments:
      - "--api.insecure=true"
    service:
      type: NodePort
    ports:
      web:
        nodePort: 32080
      websecure:
        nodePort: 32443
    nodeSelector:
      ingress-controller: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: IngressRoute
        metadata:
          name: traefik-external-dashboard
        spec:
          entryPoints:
            - web
          routes:
            - kind: Rule
              match: "Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
              services:
                - kind: TraefikService
                  name: api@internal