---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/weave-gitops
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
