---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-certs
  namespace: linkerd
spec:
  interval: 60m
  chart:
    spec:
      chart: linkerd-certs
      sourceRef:
        kind: HelmRepository
        name: linkerd-certs
        namespace: linkerd
      interval: 48h
