---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 24h
  url: https://helm.linkerd.io/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd-certs
  namespace: linkerd
spec:
  interval: 24h
  url: https://erumble.github.io/helm-charts
