apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flamingo
  namespace: argocd
spec:
  values:
    configs:
      params:
        server.insecure: true
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: argocd.localhost
    extraObjects:
      - apiVersion: argoproj.io/v1alpha1
        kind: AppProject
        metadata:
          name: applications
          namespace: argocd
        spec: {}
      - apiVersion: argoproj.io/v1alpha1
        kind: AppProject
        metadata:
          name: controllers
          namespace: argocd
        spec: {}
      - apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: cert-manager
          namespace: argocd
          labels:
            app.kubernetes.io/managed-by: flamingo
            flamingo/workload-name: cert-manager
            flamingo/workload-type: "HelmRelease"
            flamingo/source-type: "HelmRepository"
            flamingo/destination-namespace: "cert-manager"
            flamingo/cluster-name: "in-cluster"
          annotations:
            weave.gitops.flamingo/base-url: "http://localhost:9001"
            weave.gitops.flamingo/cluster-name: "Default"
        spec:
          destination:
            namespace: cert-manager
            server: https://kubernetes.default.svc
          project: controllers
          source:
            chart: cert-manager
            repoURL: https://charts.jetstack.io
            targetRevision: "*"
            helm:
              releaseName: cert-manager
          syncPolicy:
            syncOptions:
            - ApplyOutOfSyncOnly=true
            - FluxSubsystem=true
