apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  chart:
    spec:
      version: 30.12.*
  values:
    dashboard:
      enforcedHostRegexp: "^(linkerd.localhost|localhost:.*)$"
