apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  values:
    ingress:
      enabled: true
      host: "backstage.localhost"
    backstage:
      appConfig:
        techdocs:
          builder: local
          generator:
            runIn: local
          publisher:
            type: local
        app:
          baseUrl: http://backstage.localhost
        backend:
          baseUrl: http://backstage.localhost
          auth:
            dangerouslyDisableDefaultAuthPolicy: true
            providers:
              guest:
                dangerouslyAllowOutsideDevelopment: true
            externalAccess:
            - type: legacy
              options:
                secret: letmein
                subject: human
