apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo
  - ../../base/backstage
patches:
  - path: podinfo.values.yaml
    target:
      kind: HelmRelease
      name: podinfo
      namespace: podinfo
  - path: backstage.values.yaml
    target:
      kind: HelmRelease
      name: backstage
      namespace: backstage
