apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      version: 32.1.*

  values:
    gateway:
      listeners:
        web:
          namespacePolicy: All

    providers:
      kubernetesGateway:
        enabled: true

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: "Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
        entryPoints: ["traefik", "web"]

    additionalArguments:
      - "--api.insecure=true"

    nodeSelector:
      ingress-controller: "true"

    ports:
      web:
        nodePort: 32080
      websecure:
        nodePort: 32443

    service:
      type: NodePort

    tolerations:
      - effect: NoSchedule
        key: "node-role.kubernetes.io/control-plane"
        operator: Exists
