---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  toolkit.fluxcd.io/tenant: sre-team
resources: # 👋 Start adding the resources you want to sync here
- traefik-dashboard.yaml
- k8s-dashboard-cert.yaml
