---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  toolkit.fluxcd.io/tenant: sre-team
resources:
  - ../../base/cert-manager
  - ../../base/linkerd
  - ../../base/traefik
  - ../../base/weave-gitops
  - ./traefik-ingressroute.yaml
patches:
  - path: weave-gitops-values.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
      namespace: traefik
