apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
      enabled: true
      className: traefik
      hosts:
        - host: podinfo.localhost
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: podinfo-tls
          hosts:
            - podinfo.localhost
