apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/weave-gitops
patches:
  - path: weave-gitops-values.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system