---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: linkerd-jaeger
spec:
  interval: 60m
  chart:
    spec:
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  values:
    webhook:
      externalSecret: true
      injectCaFrom: linkerd-jaeger/jaeger-injector
  dependsOn:
    - name: linkerd-control-plane
      namespace: linkerd
