---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 60m
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
  values:
    tap:
      externalSecret: true
      injectCaFrom: linkerd-viz/tap
    tapInjector:
      externalSecret: true
      injectCaFrom: linkerd-viz/tap-injector
    jaegerUrl: jaeger.linkerd-jaeger.svc:16686
  dependsOn:
    - name: linkerd-jaeger
      namespace: linkerd-jaeger
