---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    linkerd.io/extension: viz
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-jaeger
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    linkerd.io/extension: jaeger
